spring:
  application:
    name: notification-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 6060
  contextPath: notification-service
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
