spring:
  application:
    name: budget-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 8080
  contextPath: budget-service
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      user:
        maxAttempts: 4
        waitDuration: 3s
        enableExponentialBackoff: true
